config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'

  match "home/search", to: "home#search", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/git_account.rb
class GitAccount < ApplicationRecord
	has_many :repositories
end

app/models/repository.rb
class Repository < ApplicationRecord
	belongs_to :git_account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

  end

  def search
  	if user_name.present?
		@git_user = GitAccount.where(user_name: user_name.downcase).first

		if @git_user.present?
			@repositories = Repository.where(git_account_id: @git_user.id)
		else
			details = user_details
			if details["message"].present?
				@error_message = "'#{user_name}' not exist in Gitlab "
			else
				repositories = user_repositories
				@git_user = GitAccount.create(user_name: user_name.downcase, user_id: details["id"], profile_url: details["html_url"], location: details["location"])
				_rep = []
				repositories.each do |repository|
					_rep << Repository.new( repository_url: repository["html_url"] )
				end
				@git_user.repositories << _rep if _rep.present?
				@repositories = Repository.where(git_account_id: @git_user.id)
			end
		end
	end
	render :index
  end

  private

	def user_details
		result = HTTParty.get("https://api.github.com/users/#{user_name}")
		JSON.parse(result.response.body)
	end

	def user_repositories
		result = HTTParty.get("https://api.github.com/users/#{user_name}/repos")
		JSON.parse(result.response.body)
	end

	def user_name
		(params.permit!)[:user_name]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_git_user.html.erb
<div class="row marginTOP">
    <div class="col-sm-12 col-md-3 col-lg-3 text-center">
        <i class="fa fa-user-circle-o fa-5x"></i>
    </div>
            
        
	<div class="col-sm-12 col-md-9 col-lg-9" >
		<label ><b>Name:</b></label> 
		<p><%= @git_user.user_name %> </p>
		<label><b>Profile Url:</b></label> 
		<p><%= link_to @git_user.profile_url, @git_user.profile_url, :target => "_blank" %> </p>
		<label><b>Location:</b></label> 
		<p><%= @git_user.location || "Location Not Mentioned" %> </p>
		<label><b>Repositories:</b></label><br>
		<% @repositories.each do |rep| %>
			<p><%= link_to rep.repository_url, rep.repository_url, :target => "_blank" %></p>
		<% end %>
	</div>
</div>

app/views/home/index.html.erb
<div class="container">
    <%= form_tag home_search_url do %>
        <div class= "row marginTOP">
            <label class="col-md-3 col-sm-12 textAlign" style="padding-left: 2px;">Enter any Github username </label>
            <div class= "col-md-7 col-sm-12 text-center" style="padding-left: 2px; padding-right: 2px">
                <%= text_field_tag :user_name, (@git_user.try(:user_name) || ""), class: 'form-control' %>
            </div>
            <div class= "col-md-2 col-sm-12 text-center" style="padding-left: 2px;">
                <%= submit_tag("Search", :id=>"search", :class=>"btn btn-search", :name=>"submit") %>
            </div>
        </div>
    <% end %>
    <% if @git_user.present? %>
      <%= render 'git_user' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitAccountFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>